services:
  web:
    command: >
      sh -c "chmod +x /app/entrypoint.sh &&
             /app/entrypoint.sh gunicorn main.wsgi:application -c gunicorn.conf.py --bind 0.0.0.0:8000"
    environment:
      - LOAD_FIXTURES=1
